language: node_js
node_js:
  - '12'
before_install:
  - npm config set registry https://npm.americanwhitewater.org
stages:
- lint
- test
- build
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
        - npm run coveralls
    - stage: build
      script:
        - npm run build
