language: node_js
node_js:
  - '11'
stages:
- lint
- test
- build
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
        - npm run coveralls
    - stage: build
      script:
        - npm run build
