version: '3'
services:
  # continuously rebuild assets when sources change
  # local only
  app-watcher:
    build:
      context: .
      dockerfile: docker/watching/watcher.Dockerfile
    image: wh2o/app-watcher
    ports:
      - 9669:9669
    working_dir: /usr/src
    command: bash -c "./docker/watching/watch.sh"
    env_file:
      - docker/app.env
    volumes:
      - built_app:/usr/src/dist
      - node_modules_app:/usr/src/node_modules
      - components_app:/usr/src/components
      - ./docker:/usr/src/docker
      - ./public:/usr/src/public
      - ./server:/usr/src/server
      - ./src:/usr/src/src
      - ./.bitmap:/usr/src/.bitmap
      - ./.env:/usr/src/.env
      - ./.eslintrc.js:/usr/src/.eslintrc.js
      - ./babel.config.js:/usr/src/babel.config.js
      - ./jest.config.js:/usr/src/jest.config.js
      - ./package.json:/usr/src/package.json:delegated
      - ./tsconfig.json:/usr/src/tsconfig.json
      - ./vue.config.js:/usr/src/vue.config.js
volumes:
  node_modules_app:
  components_app:
  built_app:
