name: Merge Review Test Build

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14

      - name: NPM Install
        run: npm ci --ignore-scripts

      - name: Linting
        run: npm run lint

      - name: Unit Tests
        run: npm run test:unit

      - name: NPM Build
        run: npm run build

      - name: Create New Version
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # replace GITHUB_TOKEN with access token that has required permissions
