name: Merge Review Test Build

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: node Version Check
        run: node --version

      - name: Npm version check
        run: npm --version

      - name: NPM Install
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Unit Tests
        run: npm run test:unit

      - name: NPM Build
        run: npm run build
