name: Merge Review Test Build

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup docker image
        uses: docker://node:12.18.3

      - uses: actions/checkout@v2

      - name: Set NPM Registry
        run : npm config set registry https://npm.americanwhitewater.org

      - name: NPM Install
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Unit Tests
        run: npm run test:unit

      - name: NPM Build
        run: npm run build
