name: Merge Review Test Build

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14

      - name: NPM Install
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Unit Tests
        run: npm run test:unit

      - name: NPM Build
        run: npm run build
